name: test_gcd
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: action/checkout@v4
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
      - name: Run tests
        run: ./test_gcd.bash